installedESLint: true

extends:
  - google

parserOptions:
  sourceType: module
  ecmaVersion: 6

env:
  browser: true
  node: true
  jasmine: true

rules:
  arrow-parens: off
  no-var: warn
  max-statements-per-line: off
  max-len:
    - error
    - 100
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle: off
  spaced-comment: off
  valid-jsdoc: off
